version: '3.8'
services:
  app:
    build: .
    container_name: movie-backend-app
    env_file: .env
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: movie-backend-db
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: movie-backend-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
